apiVersion: "gcp.hightowerlabs.com/v1"
kind: CloudRunService
metadata:
  name: httpbin
spec:
  image: "gcr.io/hightowerlabs/httpbin"
  cpu: 1
  concurrency: 50
  memory: "256Mi"
  regions:
    - "us-west1"
